### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by 4F2E4A2E** [ascendro/GreenshotRedmineUploader#1]
First of all thank you guys for this plugin. It is great to work with Greenshot and Redmine.

Is there any possibility to support SSL?

I have Redmine setup with SSL only and i am not able to connect to it using SSL at all.
Any config that could be set?

![2014-03-17_12_22_23-greenshotredmineuploader_0 0 3](https://f.cloud.github.com/assets/64590/2435430/c9be5546-adc6-11e3-99dc-c7a4e0f97a00.png)

Here i found something on the web were they are just ignoring the certificate check:
http://foren.activevb.de/archiv/vb-net/thread-95623/beitrag-95627/Re-HTTPS-Webrequest/

``` .net
Public Class Form1
    Private Sub Button1_Click(sender As System.Object, e As System.EventArgs) Handles Button1.Click
        ServicePointManager.ServerCertificateValidationCallback = New System.Net.Security.RemoteCertificateValidationCallback(AddressOf AcceptCert)

        Dim hreq As HttpWebRequest = CType(HttpWebRequest.Create("https://192.168.2.1/top_status.stm"), HttpWebRequest)
        Dim hres As HttpWebResponse = CType(hreq.GetResponse(), HttpWebResponse)
        Dim s As Stream = hres.GetResponseStream()
        Dim sr As New StreamReader(s)
        Dim html As String = sr.ReadToEnd()

        sr.Close()
        s.Close()

        File.WriteAllText(My.Computer.FileSystem.SpecialDirectories.Desktop & "\test.txt", html)
    End Sub

    Private Function AcceptCert(ByVal sender As Object, ByVal cert As System.Security.Cryptography.X509Certificates.X509Certificate, _
                                ByVal chain As System.Security.Cryptography.X509Certificates.X509Chain, _
                                ByVal errors As System.Net.Security.SslPolicyErrors) As Boolean
        Return True
    End Function
End Class
```

**Comment by MichaelKling** [comment]
Hey,

the error message 

---

## Error while Syncing.

## The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

## OK   

looks more like the certificate is not issued by CA in your list of trusted CA's and therefore declined. Is that the case for your redmine installation?

**Comment by MichaelKling** [comment]
I checked the code of the api library i'm using ( https://code.google.com/p/redmine-net-api/source/browse/trunk/Api/RedmineWebClient.cs ) and i'm now 90% sure that it can be solved with that: http://stackoverflow.com/questions/536352/webclient-https-issues

**Comment by MichaelKling** [comment]
I implemented the solution in an extra branch: https://github.com/ascendro/GreenshotRedmineUploader/tree/noSSLVerification

please try it out, if it solves your issue i will implement it as an option into the master branch.

**Comment by 4F2E4A2E** [comment]
My certificate is certainly not issued by the CA, but it will not ever be, so thank you for the fix!

![2014-03-17_14_41_04](https://f.cloud.github.com/assets/64590/2436369/18238ed2-adda-11e3-9b97-b1846e5747ec.png)

**Comment by MichaelKling** [comment]
great - it will go onto the list for version 4.

**Comment by MichaelKling** [comment]
This is now an optional feature in version 0.4

**Comment by 4F2E4A2E** [comment]
👍
